/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoinProfile {
  'name' : string,
  'description' : string,
  'logoUrl' : string,
  'symbol' : string,
}
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'createdAt' : bigint,
  'seller' : Principal,
  'updatedAt' : bigint,
  'buyer' : [] | [Principal],
  'priceICP' : number,
  'amount' : bigint,
}
export type ListingStatus = { 'Open' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface MarketStats {
  'currentPrice' : number,
  'circulatingSupply' : number,
  'marketCap' : number,
  'volume24h' : number,
  'totalSupply' : number,
  'priceChange24h' : number,
  'allTimeHigh' : number,
}
export interface PricePoint { 'timestamp' : bigint, 'price' : number }
export interface Transaction {
  'id' : bigint,
  'to' : Principal,
  'from' : Principal,
  'memo' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'principal' : Principal,
  'totalReceived' : bigint,
  'balance' : bigint,
  'totalSent' : bigint,
  'transferCount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPricePoint' : ActorMethod<[PricePoint], undefined>,
  'adminResolve' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelListing' : ActorMethod<[bigint], undefined>,
  'claimInitialAdmin' : ActorMethod<[], undefined>,
  'clearPriceHistory' : ActorMethod<[], undefined>,
  'confirmSale' : ActorMethod<[bigint], undefined>,
  'createListing' : ActorMethod<[bigint, number], bigint>,
  'getAllUserStats' : ActorMethod<[], Array<UserStats>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinProfile' : ActorMethod<[], CoinProfile>,
  'getFixedTotalSupply' : ActorMethod<[], number>,
  'getFixedTotalSupplyNat' : ActorMethod<[], bigint>,
  'getLatestPricePoint' : ActorMethod<[], [] | [PricePoint]>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getMarketStats' : ActorMethod<[], MarketStats>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getPriceHistory' : ActorMethod<[], Array<PricePoint>>,
  'getRecentTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTaxAccount' : ActorMethod<[], [] | [Principal]>,
  'getTopHolders' : ActorMethod<[bigint], Array<[Principal, bigint]>>,
  'getTotalMinted' : ActorMethod<[], bigint>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminBeenClaimed' : ActorMethod<[], boolean>,
  'initiatePurchase' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintTokens' : ActorMethod<[Principal, bigint], undefined>,
  'registerUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTaxAccount' : ActorMethod<[Principal], undefined>,
  'transfer' : ActorMethod<[Principal, bigint], undefined>,
  'updateCoinProfile' : ActorMethod<[CoinProfile], undefined>,
  'updateCoinProfileAndMarketStats' : ActorMethod<
    [CoinProfile, MarketStats],
    undefined
  >,
  'updateMarketStats' : ActorMethod<[MarketStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];