/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PricePoint = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CoinProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'symbol' : IDL.Text,
});
export const MarketStats = IDL.Record({
  'currentPrice' : IDL.Float64,
  'circulatingSupply' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'volume24h' : IDL.Float64,
  'totalSupply' : IDL.Float64,
  'priceChange24h' : IDL.Float64,
  'allTimeHigh' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPricePoint' : IDL.Func([PricePoint], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearPriceHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinProfile' : IDL.Func([], [CoinProfile], ['query']),
  'getLatestPricePoint' : IDL.Func([], [IDL.Opt(PricePoint)], ['query']),
  'getMarketStats' : IDL.Func([], [MarketStats], ['query']),
  'getPriceHistory' : IDL.Func([], [IDL.Vec(PricePoint)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCoinProfile' : IDL.Func([CoinProfile], [], []),
  'updateCoinProfileAndMarketStats' : IDL.Func(
      [CoinProfile, MarketStats],
      [],
      [],
    ),
  'updateMarketStats' : IDL.Func([MarketStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PricePoint = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CoinProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const MarketStats = IDL.Record({
    'currentPrice' : IDL.Float64,
    'circulatingSupply' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'volume24h' : IDL.Float64,
    'totalSupply' : IDL.Float64,
    'priceChange24h' : IDL.Float64,
    'allTimeHigh' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPricePoint' : IDL.Func([PricePoint], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearPriceHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinProfile' : IDL.Func([], [CoinProfile], ['query']),
    'getLatestPricePoint' : IDL.Func([], [IDL.Opt(PricePoint)], ['query']),
    'getMarketStats' : IDL.Func([], [MarketStats], ['query']),
    'getPriceHistory' : IDL.Func([], [IDL.Vec(PricePoint)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCoinProfile' : IDL.Func([CoinProfile], [], []),
    'updateCoinProfileAndMarketStats' : IDL.Func(
        [CoinProfile, MarketStats],
        [],
        [],
      ),
    'updateMarketStats' : IDL.Func([MarketStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };