/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoinProfile {
  'name' : string,
  'description' : string,
  'logoUrl' : string,
  'symbol' : string,
}
export interface MarketStats {
  'currentPrice' : number,
  'circulatingSupply' : number,
  'marketCap' : number,
  'volume24h' : number,
  'totalSupply' : number,
  'priceChange24h' : number,
  'allTimeHigh' : number,
}
export interface PricePoint { 'timestamp' : bigint, 'price' : number }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPricePoint' : ActorMethod<[PricePoint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearPriceHistory' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinProfile' : ActorMethod<[], CoinProfile>,
  'getLatestPricePoint' : ActorMethod<[], [] | [PricePoint]>,
  'getMarketStats' : ActorMethod<[], MarketStats>,
  'getPriceHistory' : ActorMethod<[], Array<PricePoint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCoinProfile' : ActorMethod<[CoinProfile], undefined>,
  'updateCoinProfileAndMarketStats' : ActorMethod<
    [CoinProfile, MarketStats],
    undefined
  >,
  'updateMarketStats' : ActorMethod<[MarketStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];